//.slideDown();はアニメーションで上から表示
//.slideUp();下から表示
//.show();cssで非表示の要素をjQueryで表示
//.hide();表示されている要素をjQueryで非表示
$(function(){
  $('.box1').on('click',function(){
    $('.box1').addClass('box1-ext');
  });
  $('.box1').mouseout(function(){
    $('.box1').removeClass('box1-ext');
  });
});